import { METADATA } from '@configs/metaData';

export const PROJECTLIST: ProjectType[] = [
  {
    projectName: 'Tech Blog',
    description: '개발하며 배운 것과 생각들을 기록하는 블로그',
    projectLink: METADATA.url,
    techStackList: [
      'Next.js',
      'TypeScript',
      'React',
      'Chakra-Ui',
      'Vercel',
      'Next-Contentlayer',
    ],
    detailDesc: [
      'next-contentlayer를 사용하여 mdx파일을 코드로 변환하여 마크다운 형식으로 변환하는 코드 구현',
      'Chakra-Ui를 사용해 디자인 시스템 구축, 다크모드 적용',
      'Vercel을 이용한 간편한 배포 환경 구축',
      '블로그가 검색엔진에 잘 노출 될 수 있도록 SEO 최적화',
    ],
  },
  {
    projectName: '놀면서 배우는 심리학',
    description: '누구나 사용할 수 있는 심리학 플랫폼',
    projectLink: 'https://www.nolsim.co.kr/',
    techStackList: [
      'React',
      'React-Query',
      'React-Hook-Form',
      'TypeScript',
      'Axios',
      'Next.js',
      'Redux-Toolkit',
      'Chakra-Ui',
    ],
    detailDesc: [
      'React-Hook-Form을 사용하여 form관련 페이지 코드 작성',
      '서버 데이터는 React-Query를 사용하여 핸들링.',
      'Client측 데이터는 RTK로 관리.',
      '작성중이던 포스트 임시저장 기능 구현',
    ],
  },
  {
    projectName: 'Asiana IDT GATE26',
    description: 'Asiana IDT의 항공 플랫폼 APP',
    projectLink: 'https://web.gate26.co.kr/',
    techStackList: [
      'JavaScript',
      'TypeScript',
      'Next.js',
      'React',
      'React.Query',
      'Redux-Toolkit',
      'Chakra-Ui',
      'Axios',
      'React-Hook-Form',
    ],
    detailDesc: [
      '메인페이지 설계, 동행찾기 페이지 리뉴얼 작업',
      '동행찾기 페이지에서 쿼리스트링을 이용하여, 따로 전역상태 라이브러리를 쓰지 않더라도 필터링 기능 구현',
      '불필요하게 중복되는 코드들 하나의 컴포넌트로 모듈화 하는 작업',
      '여러 페이지에서 잘 작동하지 않았던 무한 스크롤 이슈 해결',
      '내 티켓 페이지 리뉴얼 작업, 티켓을 누르면 열리는 티켓 디테일 팝업 리뉴얼 작업',
      '알림페이지의 항공편중에 하나를 클릭시 티켓페이지로 넘어오면서 티켓 디테일 팝업이 안뜨던 이슈 해결',
      '내 티켓 페이지에서 티켓 사진 공유시, 티켓 사진 테두리가 이상하게 보이는 이슈 해결',
      '서버로부터 데이터 받아오기까지 빈 화면이 아닌, 스켈레톤으로 로딩 처리',
    ],
  },
];
